#!/bin/sh

### BEGIN INIT INFO
# Provides:          gpio_interface
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO
#
# Author: David Slama <dslam127@gmail.com>

# fan low
echo 16 >/sys/class/gpio/export
echo out > /sys/class/gpio/gpio16/direction
# fan high
echo 17 >/sys/class/gpio/export
echo out > /sys/class/gpio/gpio17/direction
