#!/bin/sh

### BEGIN INIT INFO
# Provides:          hdd_led_activity
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Monitor Linkstation LS-CHL
# Description:       Enable service provided by daemon.
### END INIT INFO

#
# hddled:
# - monitors hdd activity and displays it using info/error led
#
# Author: David Slama <dslam127@gmail.com>
# Date: 7 November 2015
#
# Credits:
# This is not all my work, but I can't find the original source.

. /lib/lsb/init-functions

LED_INFO=/sys/devices/gpio_leds/leds/linkstation\:amber\:info/brightness

run_daemon()
{       # this part is not my code only modified
        log_daemon_msg "Starting HDD activity LED" "hdd_led_activity" || true
        iostat -z -d 1 sda | sed -u -e '1d' -e 's/Device.*/0/' -e 's/sd.*/1/' -e '/^$/d' > $LED_INFO &
        log_end_msg 0 || true
}

kill_daemon()
{
        log_daemon_msg "Stopping HDD activity LED" "hdd_led_activity" || true
        pkill iostat
        log_end_msg 0 || true
}

# Main loop
case $1 in
        start)
                run_daemon
                ;;
        stop)
                kill_daemon
                ;;
        restart|force-reload)
                $0 stop && sleep 2 && $0 start
                ;;

        *)
                echo "Usage: $0 {start|stop|restart|force-reload}"
                exit 2
                ;;
esac
