#!/bin/sh

### BEGIN INIT INFO
# Provides:          shutdown_monitor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts or stops the daemon watching the power switch
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

# Author: David Slama <dslam127@gmail.com>
# Date: 7 November 2015

. /lib/lsb/init-functions

DESC="Shutdown Switch Monitor"
DAEMON=/usr/local/sbin/shutdown_daemon
NAME=shutdown_daemon

case $1 in
    start)
        log_daemon_msg "Starting shutdown monitor" "shutdown_monitor" || true
        $DAEMON &
        log_end_msg 0 || true
    ;;
    stop)
        log_daemon_msg "Stopping shutdown monitor" "shutdown_monitor" || true
        pkill $NAME
        log_end_msg 0 || true
    ;;
    restart)
        $0 stop
        sleep 2
        $0 start
    ;;
    *)
        echo "arguments: start, stop, and restart"
    ;;
esac
