#!/bin/bash

# shell script to control the red info led (alarm led)
PIN=/sys/devices/gpio_leds/leds/linkstation\:red\:alarm/trigger

case $1 in
    on)
        echo timer > $PIN
    ;;
    off)
        echo none > $PIN
    ;;
    state)
        if [ $(cat $PIN) -eq 0 ]; then
            echo "off"
        else
            echo "on"
        fi
    ;;
    *)
        echo "arguments: on, off, or state"
    ;;
esac
