#!/usr/bin/python
import select
import struct
import time
import sys
import os

infile_path = "/dev/input/event0"

#long int, long int, unsigned short, unsigned short, unsigned int
FORMAT = 'llHHI'
EVENT_SIZE = struct.calcsize(FORMAT)

#open file in binary mode
in_file = open(infile_path, "rb")

event = in_file.read(EVENT_SIZE)
want_shutdown = False
while event:
    (tv_sec, tv_usec, type, code, value) = struct.unpack(FORMAT, event)

    if type != 0 or code != 0 or value != 0:
        print("Event type %u, code %u, value %u at %d.%d" % \
            (type, code, value, tv_sec, tv_usec))
        if type == 5 and code == 0 and value == 0:
            want_shutdown = True
        else:
            want_shutdown = False
    else:
        # Events with code, type and value == 0 are "separator" events
        print("===========================================")

    if want_shutdown:
        r, w, e = select.select([ in_file ], [], [], 0.5)
        if in_file not in r:
             print("Shutdown now\n")
             os.system('shutdown -h now')
    event = in_file.read(EVENT_SIZE)

in_file.close()
